### ISSUE TITLE
Connection Initialization issue

### ISSUE THREAD

**Issue by grimy86** [ag-86/DataVista#8]
It's unclear whether some objects of the connection class can be null initialized or not.
A simple if statement revisit will suffice.

**Comment by smellilac** [comment]
> It's unclear whether some objects of the connection class can be null initialized or not. A simple if statement revisit will suffice.

Hello!

It seems that your project is intended exclusively for your machine.
There was a problem opening the project (Visual Studio), The project file 'C:\Users\User\source\repos\DVC\DVC.vcxproj' has been moved, renamed, or is missing from your computer.

Moreover, the project itself is located in another directory
C:\Users\User\source\repos\DataVista

Please provide instructions on how to solve this problem

**Comment by grimy86** [comment]
Hello @smellilac!

Have you tried following this step?
![image](https://github.com/user-attachments/assets/8b114141-25bc-48e9-bc40-988fa983a80a)

DVC.dll can be found in https://github.com/agC86/DataVista/tree/master/x64/Release

**Comment by smellilac** [comment]
> Hello @smellilac!
> 
> Have you tried following this step? ![image](https://private-user-images.githubusercontent.com/105457539/352773764-8b114141-25bc-48e9-bc40-988fa983a80a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNTY0ODIsIm5iZiI6MTcyMjE1NjE4MiwicGF0aCI6Ii8xMDU0NTc1MzkvMzUyNzczNzY0LThiMTE0MTQxLTI1YmMtNDhlOS1iYzQwLTk4OGZhOTgzYTgwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOFQwODQzMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMTJjZjlkN2Q3NzkyNGU5OGQxMGU5NTA2YTc4ZTk2YzVjZmQ0NWNkOGE0YWIzNjVmNjU3ZDM4ZGE2ZDY4YzEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5lO1WSmeblxIqfD2Y8Wkyh-MYpY3yIL7zuWCqAv2HOo)
> 
> DVC.dll can be found in https://github.com/agC86/DataVista/tree/master/x64/Release

Yes, I did. 
But nothing changed.
 I wrote about it because Visual Studio requires loading DVC.vcxproj first, which is typical not for C#, but for C++. And because the file must be in a strange directory.

**Comment by grimy86** [comment]
I know it's a C/C++ dll to import some functions into the project. However
I think it will be better off making a separate package for it seems it's
giving you issues.
Will fix it for you today or tomorrow.

**Comment by grimy86** [comment]
@smellilac DVC.dll has been removed from the project. You should be able to build successfully now.
Here's the list of dereference issues in the project.

![image](https://github.com/user-attachments/assets/aeae9094-f20d-4ff3-8172-ce705f01fa16)

**Comment by smellilac** [comment]
Nothing changed :sweat:

![image](https://github.com/user-attachments/assets/655c88d0-2949-4be8-8006-6569fd7acc90)

**Comment by grimy86** [comment]
Your fork is outdated, it still has the DVC in there.
